### ISSUE TITLE
RequestError: {'status': 410L, 'body': 'No longer available', 'reason': ''}

### ISSUE THREAD

**Issue by aliebuck** [jjinux/party-playlist-picker#6]
Once authenticated, I get:

```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python/python_lib/versions/1/google/appengine/ext/webapp/_webapp25.py", line 715, in __call__
    handler.get(*groups)
  File "/base/data/home/apps/s~party-playlist-picker/1.361544138219890479/playlistpicker/initialization.py", line 56, in check_login
    handler_method(self, *args)
  File "/base/data/home/apps/s~party-playlist-picker/1.361544138219890479/playlistpicker/../third-party/oauth2client/appengine.py", line 235, in check_oauth
    method(request_handler, *args)
  File "/base/data/home/apps/s~party-playlist-picker/1.361544138219890479/playlistpicker/handlers/playlistshandler.py", line 34, in get
    yt_service.GetYouTubePlaylistFeed, username="default")
  File "/base/data/home/apps/s~party-playlist-picker/1.361544138219890479/playlistpicker/utils/youtube.py", line 105, in fetch_feed_and_entries
    feed = get_feed_callback(*args, **kargs)
  File "/base/data/home/apps/s~party-playlist-picker/1.361544138219890479/playlistpicker/../third-party/gdata/youtube/service.py", line 350, in GetYouTubePlaylistFeed
    return self.Get(uri, converter=gdata.youtube.YouTubePlaylistFeedFromString)
  File "/base/data/home/apps/s~party-playlist-picker/1.361544138219890479/playlistpicker/../third-party/gdata/service.py", line 1108, in Get
    'reason': server_response.reason, 'body': result_body}
RequestError: {'status': 410L, 'body': 'No longer available', 'reason': ''}
```

**Comment by aliebuck** [comment]
Might be related to https://github.com/jjinux/party-playlist-picker/issues/5
